### ISSUE TITLE
`model_dump` raised warnings when dealing with URL, Enum attribute types

### ISSUE THREAD

**Issue by zhu0619** [polaris-hub/polaris#105]
### Polaris version

0.4.1

### Python Version

3.12

### Operating System

Mac

### Installation

pip install 

### Description

There are always warnings from `to_json` function of dataset and benchmark when dealing with attributes in type httpurlString , such as curation_reference and source. 
```
UserWarning: Pydantic serializer warnings:
  Expected `url` but got `str` - serialized value may not be as expected.
```

The issue is [model_dump](https://github.com/polaris-hub/polaris/blob/1372ffb496c5ab2412e8f88e7235dbda06f96489/polaris/dataset/_dataset.py#L397) expects url  but attributes were converted to [string.](https://github.com/polaris-hub/polaris/blob/1372ffb496c5ab2412e8f88e7235dbda06f96489/polaris/utils/types.py#L68).

In that case, shall we just exclude those attributes from `model_dump` such as 
```
        serialized = self.model_dump(exclude={"cache_dir", "source", "curation_referenece"}, exclude_none=True)
        serialized["source"] = self.source
        serialized["curation_reference"] = self.curation_reference
```
or simply silence the warnings by 
```
serialized = self.model_dump(exclude={"cache_dir"}, exclude_none=True, warnings=False)
```
Similar warnings for attributes of `Enum` type, such as `task_type` and `target_type`
```
Expected `enum` but got `str` - serialized value may not be as expected
```

### Steps to reproduce

```
import pandas as pd
from polaris.dataset import Dataset

dataset  = Dataset(table=pd.DataFrame({"data_col":[1]}), curationReference="https://1233455", source="https://54321")
dataset.model_dump( exclude={"cache_dir", "table"})
```

**Comment by cwognum** [comment]
Thanks for raising the issue, @zhu0619 ! 

This seems to be due to the [`HttpUrlString` type](https://github.com/polaris-hub/polaris/blob/1372ffb496c5ab2412e8f88e7235dbda06f96489/polaris/utils/types.py#L68). I assume it's because it expects the `HttpUrl` as input, but we automatically convert this to `str` with a `AfterValidator`. I don't understand it fully, because I wouldn't expect this warning anymore...

Anyways, I think we should neither silence the warnings or exclude them from being dumped. Reading through [this GH discussion](https://github.com/pydantic/pydantic/discussions/6395#discussioncomment-8887718), it seems we should use `model_dump(mode="json")`.

**Comment by zhu0619** [comment]
> Thanks for raising the issue, @zhu0619 !
> 
> This seems to be due to the [`HttpUrlString` type](https://github.com/polaris-hub/polaris/blob/1372ffb496c5ab2412e8f88e7235dbda06f96489/polaris/utils/types.py#L68). I assume it's because it expects the `HttpUrl` as input, but we automatically convert this to `str` with a `AfterValidator`. I don't understand it fully, because I wouldn't expect this warning anymore...
> 
> Anyways, I think we should neither silence the warnings or exclude them from being dumped. Reading through [this GH discussion](https://github.com/pydantic/pydantic/discussions/6395#discussioncomment-8887718), it seems we should use `model_dump(mode="json")`.

I tried `model_dump(mode="json")` and `model_dump_json` which still raises the warnings.

**Comment by cwognum** [comment]
😮‍💨

What about this then:

```python
HttpUrlAdapter = TypeAdapter(HttpUrl)
HttpUrlString: TypeAlias = Annotated[str, BeforeValidator(lambda v: HttpUrlAdapter.validate_python(v) and v)]
```

This way, we simply save the URLs as strings, but still validate if they are valid URLs.

**Comment by zhu0619** [comment]
Yeah, it will work if the type accept `str` for validation.  
But, it allows any string input, right? Do we want that?

**Comment by cwognum** [comment]
It will indeed allow for `str` input, but it will validate whether the `string` is a valid `HttpUrl` _without_ converting the `str` to a `HttpUrl`.

**Comment by zhu0619** [comment]
That works. Could you commit the changes?
