### ISSUE TITLE
HTTPStatusError: Client error '404 Not Found' when loading benchmark

### ISSUE THREAD

**Issue by emotionor** [polaris-hub/polaris#115]
**Description:**

I encountered an issue when trying to load a benchmark using the `polaris` library. The following code snippet produces an HTTPStatusError:

```python
import polaris as po

benchmark = po.load_benchmark("polaris/hello_world_benchmark")
```

**Error Message:**

```
HTTPStatusError: Client error '404 Not Found' for url 'https://polarishub.io/api/v1/benchmark/polaris/hello_world_benchmark'
Traceback (most recent call last):
  File ~/miniconda3/lib/python3.11/site-packages/polaris/hub/client.py, line 136, in PolarisHubClient._base_request_to_hub
    response.raise_for_status()
  ...
  File ~/miniconda3/lib/python3.11/site-packages/httpx/_models.py, line 761, in response.raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
```

**Environment:**

- Python version: 3.11
- Polaris version: 0.5.0
- Operating System: Linux

**Additional Information:**

It seems like the URL `https://polarishub.io/api/v1/benchmark/polaris/hello_world_benchmark` might be incorrect or the benchmark is not available on the server.
In addition to that, I've tried other datasets such as `polaris/adme-fang-1`, and they all come up with the same 404 error.
![img_v3_02c7_d580a811-a1db-4c09-be20-61e85d083b5g](https://github.com/polaris-hub/polaris/assets/39021445/3380cbe8-66a0-4213-af3c-8272fa73d32b)

**Comment by cwognum** [comment]
Hi @emotionor, thanks for reporting!

I can reproduce the issue and am looking into it.

**Comment by cwognum** [comment]
It seems we use `hello_world_benchmark` in the documentation. That's something we should fix! Thanks for reporting!

**Comment by cwognum** [comment]
We updated the docs in #117 . Let me know if that helps, @emotionor!

**Comment by robotcator** [comment]
Hi, @cwognum can you explain the split method when using get_train_test_split after load_benchmark?

**Comment by emotionor** [comment]
@cwognum Thank you very much for your assistance in resolving the issue. The solution you provided worked perfectly. I appreciate your help and the great work you do in maintaining this project.

**Comment by cwognum** [comment]
> Hi, @cwognum can you explain the split method when using get_train_test_split after load_benchmark?

Hi @robotcator , happy to answer your question, but this is not the best place to ask. Would you mind posing the question in [our Discord](https://discord.gg/vBFd8p6H7u) or in a [Github Discussion](https://github.com/polaris-hub/polaris/discussions)? That way, it's easier for others with similar questions to learn from your question as well! Thanks!
