### ISSUE TITLE
Optimize field validator for the `split` field in the `BenchmarkSpecification` class

### ISSUE THREAD

**Issue by Andrewq11** [polaris-hub/polaris#127]
# Context

Currently, the `split` field validator runs a series of iterative checks to determine whether a user has specified valid train and test rows. These checks work fine for datasets which contain a reasonable number of rows (thousands), but begin to take exceedingly long when run on datasets with millions of rows. 

For context, a `Benchmark` object containing a dataset with 200,000,000 rows took greater than 30 minutes to initialize due to this validation step. When this step was removed, it took less than 5 minutes.

# Description

This validation step must be optimized to reduce the time it takes to complete. This will likely come in the form of ensuring that all current checks which are in place are required, refactoring existing checks with a focus on removing redundant work and improving time complexity, and also deciding whether there are different business rules we can use to judge the validity of the `split` field.

# Acceptance Criteria

- Time to init a benchmark object takes < 10 minutes with a dataset containing 200,000,000 rows

# Links

- [Link to validation step](https://github.com/polaris-hub/polaris/blob/main/polaris/benchmark/_base.py#L167)

**Comment by jstlaurent** [comment]
I have a strong suspicion that this is the worst offender:
```python
# The train and test indices do not overlap
if any(i in train_indices for i in test_indices):
    raise InvalidBenchmarkError("The predefined split specifies overlapping train and test sets")
```

Maybe building the sets of indices first, and then using them would yield better perf. Something like:
```python
@field_validator("split")
def _validate_split(cls, v: SplitType, info: ValidationInfo):
    """
    Verifies that:
      1) There is at least two, non-empty partitions
      2) All indices are valid given the dataset
      3) There is no duplicate indices in any of the sets
      3) There is no overlap between the train and test set
    """
    train_idx_list = v[0]
    test_idx_list = list(i for part in v[1].values() for i in part) if isinstance(v[1], dict) else v[1]

    # There is at least two, non-empty partitions
    if len(train_idx_list) == 0 or len(test_idx_list) == 0:
        raise InvalidBenchmarkError("The predefined split contains empty partitions")
    
    train_idx_set = set(train_idx_list)
    test_idx_set = set(test_idx_list)

    # The train and test indices do not overlap
    if len(train_idx_set & test_idx_set) > 0:
        raise InvalidBenchmarkError("The predefined split specifies overlapping train and test sets")

    # Duplicate indices
    if len(train_idx_set) != len(train_idx_list):
        raise InvalidBenchmarkError("The training set contains duplicate indices")
    if len(test_idx_set) != len(test_idx_set):
        raise InvalidBenchmarkError("The test set contains duplicate indices")

    # All indices are valid given the dataset
    if info.data["dataset"] is not None:
        max = len(info.data["dataset"])
        if any(i < 0 or i >= max for i in chain(train_idx_list, test_idx_list)):
            raise InvalidBenchmarkError("The predefined split contains invalid indices")
    return v

```

**Comment by fteufel** [comment]
I've encountered this being horribly slow, would be great to have it faster.  

Also, is my understanding correct that the validation is run not just when initializing a benchmark object directly from data, but also when I download the (already validated) benchmark from the hub? Is that necessary?

**Comment by cwognum** [comment]
I ran a little experiment comparing the current list-based approach, a set based approach and `np.intersect1d`.

Here are the details of my environment: 
- Apple M2 Pro (16GB)
- OSX
- Python 3.12.3 
- NumPy 1.26.4

### Without an intersection

<details><summary>Setup code</summary>
<p>

```py
import numpy as np

n = ...
n_train = int(n * 0.8)
n_test = n - n_train

train_indices = np.arange(n_train)
test_indices = np.arange(n_test) + n_train

train_indices_set = set(train_indices)
test_indices_set = set(test_indices)
```

</p>
</details> 

| Method | N | Time | 
| --- | --- | --- | 
| `any(i in train_indices for i in test_indices)` |  1000 | 301 µs ± 5.38 µs | 
| `any(i in train_indices for i in test_indices)` |  1M | 17.2 s ± 84.2 ms | 
| `set(train_indices), set(test_indices)` | 1000 | 35.1 µs ± 442 ns | 
| `set(train_indices), set(test_indices)` | 1M |  41.2 ms ± 593 µs | 
| `test_indices_set.intersection(train_indices_set)` | 1000 | 758 ns ± 4.77 ns  | 
| `test_indices_set.intersection(train_indices_set)` | 1M |  754 µs ± 6.83 µs | 
| `any(idx in train_indices_set for idx in test_indices_set)` | 1000 |  7.49 µs ± 50.9 ns | 
| `any(idx in train_indices_set for idx in test_indices_set)` | 1M |  7.33 ms ± 63.5 µs | 
| `np.intersect1d(train_indices, test_indices)` | 1000 | 12.4 µs ± 124 ns  | 
| `np.intersect1d(train_indices, test_indices)` | 1M |  14.4 ms ± 204 µs | 

### With an intersection

<details><summary>Setup code</summary>
<p>

```py
train_indices[n_train // 2] = test_indices[0]
```

</p>
</details> 

| Method | N | Time | 
| --- | --- | --- | 
| `any(i in train_indices for i in test_indices)` |  1000 | 1.68 µs ± 12 ns | 
| `any(i in train_indices for i in test_indices)` |  1M | 85.6 µs ± 1.47 µs | 
| `set(train_indices), set(test_indices)` | 1000 |  35.8 µs ± 386 ns | 
| `set(train_indices), set(test_indices)` | 1M |  43 ms ± 607 µs | 
| `test_indices_set.intersection(train_indices_set)` | 1000 | 767 ns ± 13.3 ns  | 
| `test_indices_set.intersection(train_indices_set)` | 1M |  752 µs ± 8 µs | 
| `any(idx in train_indices_set for idx in test_indices_set)` | 1000 | 7.56 µs ± 80.3 ns  | 
| `any(idx in train_indices_set for idx in test_indices_set)` | 1M |  7.37 ms ± 59.7 µs | 
| `np.intersect1d(train_indices, test_indices)` | 1000 |  13.9 µs ± 94.2 ns | 
| `np.intersect1d(train_indices, test_indices)` | 1M |  16.4 ms ± 211 µs | 

### Conclusion
Given its way better scaling (linear!), let's switch to @jstlaurent his suggestion. There's a performance penalty for converting to sets that makes it slower for smaller datasets, but we're converting to sets already anyways and I don't think that performance penalty is practically significant.

For N = 200M indices, I get the following result: 
```
10.2 s ± 109 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by cwognum** [comment]
> Also, is my understanding correct that the validation is run not just when initializing a benchmark object directly from data, but also when I download the (already validated) benchmark from the hub? Is that necessary?

Yes, your understanding is correct. I think we could indeed switch to using [`model_construct()`](https://docs.pydantic.dev/latest/concepts/models/#creating-models-without-validation) rather than the default constructor for artifacts loaded from the Hub.

**Comment by cwognum** [comment]
I can work on a PR tomorrow, but if someone is feeling incredibly inspired in the meantime then please go ahead! 😄
