### ISSUE TITLE
Validation error for `zarrRootPath` and `zarrMd5SumManifest` on dataset upload

### ISSUE THREAD

**Issue by LFhase** [polaris-hub/polaris#145]
### Polaris version

0.7.1

### Python Version

3.10.14

### Operating System

Linux

### Installation

pip

### Description

When I follow the steps in https://polaris-hub.github.io/polaris/main/tutorials/custom_dataset_benchmark.html to create a dataset from a csv file, and upload the dataset to hub, it reports the following error:

```
Traceback (most recent call last):
  File "xx/miniconda3/envs/xxx/lib/python3.10/site-packages/polaris/hub/client.py", line 161, in _base_request_to_hub
    response.raise_for_status()
  File "xx/miniconda3/envs/xxx/lib/python3.10/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://polarishub.io/api/v1/dataset/xxxx/xxxx'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "xx/miniconda3/envs/xxx/lib/python3.10/site-packages/polaris/hub/client.py", line 496, in upload_dataset
    response = self._base_request_to_hub(
  File "xx/miniconda3/envs/xxx/lib/python3.10/site-packages/polaris/hub/client.py", line 172, in _base_request_to_hub
    raise PolarisHubError(
polaris.utils.errors.PolarisHubError: The request to the Polaris Hub failed. See the error message below for more details:
{
  "issues": [
    {
      "code": "custom",
      "message": "For Zarr datasets, both zarrContent and zarrRootPath must be provided",
      "path": [
        "zarrRootPath",
        "zarrMd5SumManifest"
      ]
    }
  ]
}
```

### Steps to reproduce

Just follow the steps https://polaris-hub.github.io/polaris/main/tutorials/custom_dataset_benchmark.html , change the dataset and owner names to myself and uncomment the dataset uploading part.

**Comment by cwognum** [comment]
Thanks for reporting this issue, @LFhase ! 

This seems related to https://github.com/polaris-hub/polaris/pull/137. We fixed the issue, but didn't release a new version yet. Let me do that now!

**Comment by cwognum** [comment]
We just release `0.7.2`. Could you try again with this version and let me know whether the issue persists?

**Comment by LFhase** [comment]
Hi @cwognum , Thank you for the update! It fixes the issue perfectly!
