### ISSUE TITLE
Enhancement: Improve the checksum for the `Dataset` (or the equality test)

### ISSUE THREAD

**Issue by cwognum** [polaris-hub/polaris#16]
When a `Dataset` contains pointer columns, we compute the checksum based on the file path instead of the file content (see [here](https://github.com/datamol-io/polaris/blob/main/polaris/dataset/_dataset.py#L237-L239)). Since we currently use the checksum to determine equality between `Dataset` objects (see [here](https://github.com/datamol-io/polaris/blob/main/polaris/dataset/_dataset.py#L274-L278)), this can lead to a weird situation like the following: 

```python
src_dataset.to_json("/home/cas/Desktop")
dst_dataset = Dataset.from_json("/home/cas/Desktop/dataset.yaml")
src_dataset == dst_dataset  # This is False
```

How could we improve this system? @hadim mentioned using the number of bytes in a file as a proxy. That would work a lot better, but I don't think that will be performant enough as datasets get large and are stored remote.

**Comment by cwognum** [comment]
@jstlaurent This seems relevant again given our discussion this morning. 

Some additional comments: 
- We will require a checksum for the Zarr directory to ensure data integrity when uploading to the Hub. 
- While it is good to keep in mind that we eventually want to support TB-sized datasets (e.g. to inform the choice of hash function), let's focus on GB-sized ones for now.
- It's worth spending some time on this now. Once we start officially supporting Zarr datasets, it will become increasingly more difficult to change this without having to maintain multiple checksum implementations. 

Our use case here is to check whether the _entire_ Zarr dataset has been successfully uploaded. As long as this is not the case, a dataset will not be visible on the Hub. It would be great to provide the user with more detailed information on what went wrong during the upload and to only retry the necessary parts, but this use case could be supported with [`zarr.convenience.copy_all`](https://zarr.readthedocs.io/en/stable/api/convenience.html#zarr.convenience.copy_all).

It seems we could use a solution based on [`zarr_checksum`](https://github.com/dandi/zarr_checksum). I commented on https://github.com/zarr-developers/zarr-python/issues/392 to explore adding this to the official Zarr repository. 

This means the hash would change if we change the chunks or if change the encoding, but I believe this is not an issue for us.

**Comment by jstlaurent** [comment]
> It seems we could use a solution based on [`zarr_checksum`](https://github.com/dandi/zarr_checksum). I commented on [zarr-developers/zarr-python#392](https://github.com/zarr-developers/zarr-python/issues/392) to explore adding this to the official Zarr repository.

I think we ended on the same issue while researching this. I wasn't sure how feasible it would be to use that lib. If it looks good, then that's a great head start.

> This means the hash would change if we change the chunks or if change the encoding, but I believe this is not an issue for us.

I think that's fair to expect and indeed, not a problem for us.
