### ISSUE TITLE
Documentation: Explain login on quickstart page

### ISSUE THREAD

**Issue by agitter** [polaris-hub/polaris#160]
### Is your feature request related to a problem? Please describe.
As a new user, I followed the quickstart guide at https://polaris-hub.github.io/polaris/stable/quickstart.html. That does not indicate that login is required, so the cryptic message
```
  File ".conda\envs\polaris\Lib\site-packages\polaris\hub\client.py", line 229, in request
    raise PolarisUnauthorizedError(response=error.response) from error
                                            ^^^^^^^^^^^^^^
AttributeError: 'MissingTokenError' object has no attribute 'response'
```
is raised when following the instructions and running `po.load_dataset`. That message itself relates to #91 because it does not indicate the problem is that I cannot load the dataset because I am not authenticated.

### Describe the solution you'd like
Add text about needing to login or add the login command to the code sample.

### Describe alternatives you've considered
N/A

### Additional context
I figured out how to login.

**Comment by Andrewq11** [comment]
Hi @agitter, thanks for pointing this out. You're very right that a section on logging in should be included in the quickstart guide. Without it, you encounter an error which we could do a much better job of handling as you've seen. PR #165 should address both of these issues. 

We've made some progress on #91 these past few weeks, and we will continue to do so going forward. Thanks again for your time in creating this issue!

**Comment by agitter** [comment]
Thanks, #165 does address this.
