### ISSUE TITLE
Curation links in datasets are broken

### ISSUE THREAD

**Issue by PatWalters** [polaris-hub/polaris#166]
### Polaris version

dev

### Python Version

N/A

### Operating System

N/A

### Installation

N/A

### Description

I tried to follow the curation links for several datasets and the links give 404 errors.   As an example see
https://polarishub.io/datasets/polaris/adme-fang-1,

### Steps to reproduce

Access the web page, click on the link

**Comment by zhu0619** [comment]
Hi @PatWalters, 
We have moved the curation notebook under [`org-Biogen` folder](https://github.com/polaris-hub/polaris-recipes/blob/main/org-Biogen/fang2023_ADME/01_polaris_adme-fang_data_curation.ipynb). 
We will update the documentation page and remove the invalid links.  
Sorry for the confusion.

**Comment by PatWalters** [comment]
Excellent!  Thank you for the quick response.
