### ISSUE TITLE
Not able to get auth token

### ISSUE THREAD

**Issue by rchebbi3** [polaris-hub/polaris#207]
### Polaris version

0.2.0

### Python Version

3.9.20

### Operating System

Linux (WSL2)

### Installation

pip install polaris-lib

### Description

Current Behaviour: After following CLI link to polaris hub login page, I get the following error
![image](https://github.com/user-attachments/assets/c8dc2133-3c6d-48f2-91c9-9b2d1114c478)
Expected behaviour: I should be able to login/create an account

### Steps to reproduce

`pip install polaris-lib`
`polaris login`

### Additional output

pip freeze output:

annotated-types==0.7.0
anyio==4.6.2.post1
asciitree==0.3.3
Authlib==1.3.2
certifi==2024.8.30
cffi==1.17.1
click==8.1.7
contourpy==1.3.0
cryptography==43.0.1
cycler==0.12.1
datamol==0.12.5
exceptiongroup==1.2.2
fasteners==0.19
filelock==3.16.1
fonttools==4.54.1
fsspec==2024.9.0
h11==0.14.0
httpcore==1.0.6
httpx==0.27.2
idna==3.10
importlib_resources==6.4.5
joblib==1.4.2
kiwisolver==1.4.7
loguru==0.7.2
markdown-it-py==3.0.0
matplotlib==3.9.2
mdurl==0.1.2
numcodecs==0.12.1
numpy==2.0.2
packaging==24.1
pandas==2.2.3
pillow==11.0.0
platformdirs==4.3.6
polaris-lib==0.2.0
pyarrow==17.0.0
pycparser==2.22
pydantic==2.9.2
pydantic-settings==2.5.2
pydantic_core==2.23.4
Pygments==2.18.0
pyparsing==3.2.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
PyYAML==6.0.2
rdkit==2024.3.5
rich==13.9.2
scikit-learn==1.5.2
scipy==1.13.1
seaborn==0.13.2
selfies==2.1.2
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
tenacity==9.0.0
threadpoolctl==3.5.0
tqdm==4.66.5
typer==0.12.5
typing_extensions==4.12.2
tzdata==2024.2
zarr==2.18.2
zipp==3.20.2

**Comment by cwognum** [comment]
Thanks for the detailed bug report, @rchebbi3. One thing that immediately stands out to me is the Polaris version. You're using `0.2.0`, but we're already at `0.8.6` and the login logic has changed quite significantly. Could you try if the issue persists with the most recent version?

**Comment by rchebbi3** [comment]
Hi, thanks for the quick response. 

The underlying issue was the python version that I was using (3.9.20). Looking at the yml file, I saw that the minimum version requirement was 3.10 and updating the python version solved the issue. It would be great if this was documented clearly in the tutorial/readme.

thanks :)

**Comment by cwognum** [comment]
Hi @rchebbi3 , happy we were able to identify the issue this quickly. I'll close this issue for now.

On the Python version: That's good feedback, thanks! We do have the minimum Python version documented in a few places already, e.g. the `pyproject.toml` and the README (see the table at the top). I believe this is pretty standard, but open to suggestions on where else we could document it.
