### ISSUE TITLE
Documentation - Quickstart "Other installation" not rendered correctly

### ISSUE THREAD

**Issue by JacksonBurns** [polaris-hub/polaris#214]
### Polaris version

0.9.0

### Python Version

None - web browser

### Operating System

None - web browser

### Installation

None - web browser

### Description

The "Other installation options" dropdown on the github.io site does not have any content:
![image](https://github.com/user-attachments/assets/8b04860b-69d6-49d0-9b0e-dbba45758e63)

but the corresponding source code does: https://github.com/polaris-hub/polaris/blob/main/docs/quickstart.md?plain=1#L13-L14

### Steps to reproduce

Visit: https://polaris-hub.github.io/polaris/stable/quickstart.html

### Additional output

BTW this issue template says "X's behavior is ..." instead of "polaris' behavior" or something like that, I think there is a field to be filled out somewhere:
![image](https://github.com/user-attachments/assets/39346cab-6b13-44ca-96a5-8a6f775043f3)

**Comment by cwognum** [comment]
Good catch! Thanks for raising this, @JacksonBurns !

**Comment by cwognum** [comment]
Should be fixed with https://github.com/polaris-hub/polaris/pull/215. 

The text below mentioning `mamba` and `pip` should have been inside of the admonition. Issue with indentation!

**Comment by cwognum** [comment]
Merged! You will see the change on the [`main` version](https://polaris-hub.github.io/polaris/main/quickstart.html) of the docs. It will also show on `stable` (the default`) once we release a new version. Thanks again for raising the issue!
