### ISSUE TITLE
Enhancement: Headless Authentication

### ISSUE THREAD

**Issue by jstlaurent** [polaris-hub/polaris#30]
# Context
We currently use a login process where a user needs to use a Web browser to authenticate, which will not work in a headless environment.

# Description
Depending on the method selected in the [Hub issue](https://github.com/valence-labs/polaris-hub/issues/71), update the library to use it.

# Acceptance Criteria
- The library is updated to support the selected headless authentication method
- It has been tested in GitHub Actions or another headless environment

# Links
- [Hub issue](https://github.com/valence-labs/polaris-hub/issues/71)

**Comment by cwognum** [comment]
@jstlaurent I say we close this! 🎉

**Comment by jstlaurent** [comment]
Closed by #221
